const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const RoomSchema = new Schema(
  {
    title: { type: String, required: true, trim: true, maxLength: 100 },
    description: {
      type: String,
      required: true,
      minLength: 50,
      maxLength: 1000,
    },
    type: {
      type: String,
      required: true,
      enum: [
        "Apartment",
        "House",
        "Condo",
        "Townhouse",
        "Studio",
        "Loft",
        "Duplex",
        "Flat",
      ],
    },
    available: { type: Boolean, required: true}, //habia un default: true a ver si no falla
    surface: { type: Number, required: true },
    bathrooms: { type: String, required: true, enum: ["0", "1", "2", "3+"] },
    roommates: { type: Number, required: true },
    publicLocation: 
      {
        type: String,
        required: true,
        enum: [
          "Andalucia",
          "Aragon",
          "Asturias",
          "Islas Baleares",
          "Canarias",
          "Cantabria",
          "Castilla-La Mancha",
          "Castilla y Leon",
          "Cataluna",
          "Extremadura",
          "Galicia",
          "Madrid",
          "Murcia",
          "Navarra",
          "La Rioja",
          "Pais Vasco",
          "Comunidad Valenciana",
        ],
      },
    province: { type: String, required: true },
    postcode: { type: String, required: true },
    petsAllowed: { type: Boolean, required: true },
    exterior: { type: Boolean, required: true },
    roommates: { type: Number, required: true },
    commoditiesRoom: [
      {
        type: String,
        required: true,
        enum: [
          "Furnished",
          "Single Bed",
          "Double Bed",
          "Private Bathroom",
          "Balcony",
          "Natural Light",
          "Working Space",
        ],
      },
    ],
    commoditiesHome: [
      {
        type: String,
        required: true,
        enum: [
          "Appliances Included",
          "Living Room",
          "Dining Room",
          "Shower",
          "Bathtub",
          "Kitchen",
          "Microwave",
          "Heating",
          "Air Conditioning",
          "Internet Wi-Fi",
          "Cable Satellite TV",
          "Washer",
          "Dryer",
          "Garage",
          "Security System",
          "Balcony Patio",
          "Garden Yard",
          "Wheelchair Accessible",
          "Elevator",
          "Pet Friendly",
          "Smoking Allowed",
          "Fitness Center",
          "Pool",
        ],
      },
    ],
    postedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    likes: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    saved: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    comments: [{ type: mongoose.Schema.Types.ObjectId, ref: "Comment" }],
    post: { type: mongoose.Schema.Types.ObjectId, ref: "Post" },
    image: [{ type: String }],
  },
  {
    timestamps: true,
  }
);
const Room = mongoose.model("Room", RoomSchema);
module.exports = Room;

/**{"title":"Lovely room in Arkansa'",
"description":"Me gosh this is a lovely place to develop oneself in the vast and ample as well as diverse craft that is cheese making.",
 "type":"Apartment",
 "available":"true",
 "surface":"200",
 "bathroom":"true",
 "publicLocation":"Madrid",
 "province":"Madrid",
 "postcode":"28011",
 "petsAllowed":"true",
 "exterior":"true",
 "roommates":"1",
 "commoditiesRoom":"Furnished",
 "commoditiesHome":"Living Room"
} */
